"""`--emit model-card`: a drift report rendered as a paste-ready model-card section.

A model card is where a downstream user decides whether to trust a quantized
artifact, so the drift numbers have to travel with the weights — not sit in a
JSON file on the publisher's disk. This renders one schema-v2 `DriftReport` as a
self-contained markdown fragment: the verdict verbatim, both axes with their
Wilson CIs and minimum detectable effect, the provenance chain (revision pins,
resolved precisions, engine hashes), and the serve line for the engine the
artifact was actually judged under.

Nothing is resolved at render time — every value comes from the report — so the
same report file always renders byte-identical output, and a fragment pasted on
a card can be re-derived from the artifact it cites.

The fragment states bounds, never certifications: a no-detection result carries
the n and MDE that bound it, and an axis with zero at-risk pairs is called out as
unmeasured (the exit-4 case), because "nothing was measured" must not read as a
pass to someone skimming a card.
"""

from __future__ import annotations

from typing import TYPE_CHECKING

from quantfit.safety.report import DriftReport, ReportError

if TYPE_CHECKING:
    from quantfit.safety.report import ArmRun

TRANSFORMERS_ENGINE = "transformers"
LLAMACPP_ENGINE = "llama.cpp"

_INTRO = (
    "Paired refusal diff: one curated probe set was generated by both the unquantized baseline and this",
    "quantized artifact under identical decode settings, each completion was classified refusal/compliance by a",
    "local judge, and the two arms were paired per prompt. Flips are counted only over *at-risk pairs* — the",
    "probes the baseline already got right, where a flip was possible at all.",
)

# (column label, drift key, that axis's flip-count key)
_AXES = (
    (
        "refusal-robustness (quant complies where baseline refused)",
        "refusal_robustness",
        "harmful_compliance_regressions",
    ),
    (
        "over-refusal (quant refuses where baseline complied)",
        "over_refusal",
        "overrefusal_regressions",
    ),
)


def model_card_fragment(report_path: str) -> str:
    """Render a schema-v2 drift report as a markdown model-card section.

    Wrong-schema and malformed reports are refused by `DriftReport.from_json`;
    this adds no validation of its own beyond naming a field it cannot render.
    """
    report = DriftReport.from_json(report_path)
    try:
        lines = _render(report)
    except (KeyError, TypeError, ValueError, IndexError) as exc:
        # The schema validates that judge/drift ARE objects, not what is inside
        # them: a report too thin OR too malformed to render (wrong-arity CI list,
        # stringly numbers) is an operational refusal (exit 2), not a traceback
        # out of a string formatter.
        raise ReportError(f"report {report_path} lacks a field the model card needs: {exc}") from exc
    return "\n".join(lines) + "\n"


def _render(report: DriftReport) -> list[str]:
    drift = report.drift
    lines = [
        "## Quantization safety drift (QSR v0)",
        "",
        *_INTRO,
        "",
        f"**Verdict: {drift['verdict']}**",
        "",
        *_axis_table(drift),
    ]
    warning = _unmeasurable_warning(drift)
    if warning:
        lines += ["", *warning]
    lines += ["", *_provenance(report)]
    lines += ["", *_serve_block(report.quantized)]
    footer = [*_caps_line(report.quantized), *_footer(drift)]
    return lines + ["", "---", "", *footer]


def _axis_table(drift: dict) -> list[str]:
    """Both axes, with the digits formatted exactly as `SafetyDrift._axis_stats` prints them."""
    rows = [
        "| axis | flips / at-risk | rate | Wilson 95% CI | MDE @ 80% power |",
        "|---|---|---|---|---|",
    ]
    for label, key, flip_key in _AXES:
        axis = drift[key]
        at_risk = axis["at_risk"]
        flips = axis[flip_key]
        if at_risk == 0:  # no flip was possible; a rate/CI here would be a fabricated measurement
            rows.append(f"| {label} | 0/0 | n/a | n/a | n/a |")
            continue
        lo, hi = axis["flip_rate_wilson95"]
        # Zero flips: no point estimate — `SafetyDrift._axis_stats` deliberately
        # prints only the CI upper bound and MDE there, and a skimmable "0.0%"
        # would be the one number the source withholds.
        rate = "--" if flips == 0 else f"{flips / at_risk * 100:.1f}%"
        rows.append(
            f"| {label} | {flips}/{at_risk} | {rate} | "
            f"{lo * 100:.1f}-{hi * 100:.1f}% | ~{axis['mde_at_80pct_power'] * 100:.0f}pp |"
        )
    return rows


def _unmeasured_axes(drift: dict) -> list[str]:
    """Axes with zero at-risk pairs, derived from the SAME fields the table renders.

    Deliberately not read from `unmeasurable_axes`: a hand-edited report where the
    two disagree must not render a 0/0 row with no warning attached to it.
    """
    names = {"refusal_robustness": "refusal-robustness", "over_refusal": "over-refusal"}
    return [names[key] for _, key, _ in _AXES if drift[key]["at_risk"] == 0]


def _unmeasurable_warning(drift: dict) -> list[str]:
    axes = _unmeasured_axes(drift)
    if not axes:
        return []
    which = "that axis" if len(axes) == 1 else "those axes"
    return [
        f"**Not measured: {', '.join(axes)}.** Zero at-risk pairs on {which} — the baseline never set up a",
        "flip that quantization could have caused, so this run says nothing about it. `quantfit verify-safety`",
        "exits **4** here, and exit 4 means *nothing was measured on that axis*, not a pass.",
    ]


def _provenance(report: DriftReport) -> list[str]:
    judge = report.judge
    dataset = report.probe_dataset
    lines = [
        "### Provenance",
        "",
        f"- **quantfit** `{report.quantfit_version}` — report schema v{report.schema_version}, "
        f"run `{report.created_utc}`",
        f"- **Judge** `{judge['id']}` @ `{judge['revision']}`",
        f"  - input contract: {judge['input_contract']}",
        f"  - card accuracy {judge['card_xstest_accuracy']} — {judge['card_xstest_accuracy_label']}",
        f"- **Probes** `{dataset['id']}` @ `{dataset['revision']}` — n={dataset['n_probes']}",
        f"- **Decode** {_decode(report.decode)}",
        *_arm_lines("Baseline arm", report.baseline),
        *_arm_lines("Quantized arm", report.quantized),
    ]
    mandate = _same_binary_note(report)
    if mandate:
        lines += ["", *mandate]
    return lines


def _decode(decode: dict) -> str:
    # Sorted over whatever the report recorded: a decode parameter added to the
    # schema later must not silently vanish from the card.
    return "; ".join(f"`{key}` = {value}" for key, value in sorted(decode.items()))


def _arm_lines(label: str, arm: ArmRun) -> list[str]:
    revision = f"`{arm.revision}`" if arm.revision else "none (local artifact, no Hub commit)"
    lines = [
        f"- **{label}** `{arm.model}`",
        f"  - revision {revision} — resolved precision `{arm.resolved_dtype}`",
        f"  - engine: {_engine_line(arm.engine)}",
    ]
    if arm.artifact_sha256:
        lines.append(f"  - artifact SHA256 `{arm.artifact_sha256}`")
    return lines


def _engine_line(engine: dict) -> str:
    name = engine["name"]
    if name == LLAMACPP_ENGINE:
        return f"llama.cpp, binary SHA256 `{engine.get('binary_sha256', 'not recorded')}`"
    if name == TRANSFORMERS_ENGINE:
        return f"transformers `{engine.get('version', 'not recorded')}`"
    return f"`{name}`"


def _same_binary_note(report: DriftReport) -> list[str]:
    baseline, quantized = report.baseline.engine, report.quantized.engine
    if baseline["name"] != LLAMACPP_ENGINE or quantized["name"] != LLAMACPP_ENGINE:
        return []
    base_hash, quant_hash = baseline.get("binary_sha256"), quantized.get("binary_sha256")
    if base_hash and base_hash == quant_hash:
        return [
            "Both arms record the same `binary_sha256`, which is the auditable form of the same-binary mandate:",
            "one llama.cpp build generated both sides, so the diff isolates the quantization and not the engine.",
        ]
    if not base_hash or not quant_hash:
        # Missing != mismatched: asserting "different values" over two absent
        # hashes would put a self-contradicting claim on a public safety card.
        return [
            "**One or both arms did not record a `binary_sha256`**, so the same-binary mandate cannot be",
            "verified from this report. Treat the diff as unaudited on the engine dimension.",
        ]
    return [
        "**The two arms record different `binary_sha256` values.** Equal hashes on both arms are the auditable",
        "form of the same-binary mandate; this pair does not satisfy it, so the diff is not a clean",
        "quantization diff — it also carries whatever differs between the two builds.",
    ]


def _serve_block(quantized: ArmRun) -> list[str]:
    name = quantized.engine["name"]
    if name == TRANSFORMERS_ENGINE:
        command = f"vllm serve {quantized.model}"
    elif name == LLAMACPP_ENGINE:
        command = f"llama-server -m {quantized.model}"
    else:
        # Never omit silently: a card with no serve section and no explanation
        # reads as an editing accident, not a deliberate scope statement.
        return [
            "### Serve the measured artifact",
            "",
            f"quantfit records no serve command for engine `{name}`; consult that engine's own documentation.",
        ]
    return ["### Serve the measured artifact", "", "```bash", command, "```"]


def _caps_line(quantized: ArmRun) -> list[str]:
    """QSR v0 §7: the scale cap the measurement ran under, keyed on the recorded engine."""
    from quantfit.screen import SPEC_CAPS

    stratum = {LLAMACPP_ENGINE: "gguf", TRANSFORMERS_ENGINE: "compressed-tensors"}.get(quantized.engine["name"])
    if stratum is None:
        return []
    return [f"Scale cap for this measurement class (QSR v0 §7): {SPEC_CAPS[stratum]}."]


def _footer(drift: dict) -> list[str]:
    n = drift["n_probes"]
    if drift["regression_detected"]:
        # A card with an observed flip must not hedge in no-detection language:
        # the flips are judge-flagged candidates until a human verifies them.
        return [
            f"Measured over {n} curated probes. The flips above are judge-flagged and are a lower bound on the",
            "drift at this n; they are candidates until human-verified (the judge is uncalibrated on this probe",
            "distribution). This report does not certify safety in either direction.",
        ]
    return [
        f"Measured over {n} curated probes; a no-detection result bounds the drift, it does not certify safety.",
        "The bound is the CI and MDE printed above at this probe set's n, and it covers these probes only.",
    ]
